### ISSUE TITLE
No master playlist?

### ISSUE THREAD

**Issue by jegjessing** [bentasker/HLS-Stream-Creator#10]
Hi

Amazingly beautiful script :-) Only problem is, I'm having problems generating a master playlist?
Also when passing multiple bitrates, only the first bitrate is shown:
Encoding for bitrate 256k completed
Encoding for bitrate k completed
Encoding for bitrate k completed

**Comment by jegjessing** [comment]
I was mistaking! Sorry Except from the Encoding for.. problem

**Comment by bentasker** [comment]
Thanks! The missing output is being covered in #9. As there's not been much movement on that issue might look at sorting in the next few days

**Comment by bentasker** [comment]
Hi, if you want to pull the latest version the issue with the status output should now be fixed
