### ISSUE TITLE
Question about ad insertion

### ISSUE THREAD

**Issue by samueleastdev** [bentasker/HLS-Stream-Creator#22]
Hi Ben,

Not an issue more of a question we are looking into adding add cue tags into our m3u8 manifest file and don't understand the process from what I understand you need to add.

```
#EXT-X-CUE-OUT:60.00
#EXT-X-CUE-IN
```

Throughout the manifest Is this possible with your repo or do you know how this would be achieved programmatically.

Feel free to just close if this is not related or doesn't interest you thought it was worth asking?

Thanks

**Comment by bentasker** [comment]
Hi,

As far as I know, it's not possible to get `ffmpeg` to do this, so you'd probably need to programatically update the manifests after processing.

The manifest, when it boils down to it, is just a text file though so you should be able to do it - it's not something I've tried though, so off the top of my head I can't really recommend the best way to do it.

Ben
