### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by LordRampantHump** [bentasker/HLS-Stream-Creator#25]
what exactly does this do that ffmpeg does not do as it is?

**Comment by bentasker** [comment]
When this script was originally written the answer was simple - HLS.

Now it's a bit more nuanced. It does segment encryption, and depending on the type/format of your source does a better job of keeping the bitrates in sync when you're outputting linear (and for others, automates handling to make it work with multiple bitrates in the first place).

Your question could be asked of _any_ wrapper for _any_ program though, and the answer will be the same. You may find straight `ffmpeg` better for your workflow, others will find this a better fit.

**Comment by LordRampantHump** [comment]
fair enough answer i guess. What i was looking for to be honest was something that would let me take better control of the file structure when creating vod from live tv inputs, something that could organize segments into daily folders and could read epg information to write the playlists for the vod
