### ISSUE TITLE
Fragmented MP4

### ISSUE THREAD

**Issue by Teranode** [bentasker/HLS-Stream-Creator#26]
Do you have any examples for fragmented mp4?

**Comment by bentasker** [comment]
Sorry, I missed this.

No, I don't have any examples to hand I'm afraid. `ffmpeg` supports it though, so it _may_ be sufficient to add `-movflags frag_keyframe+empty_moov` to `FFMPEG_FLAGS`. I suspect there are probably some other tweaks needed as well though

**Comment by Teranode** [comment]
Im still actively using the ts method, but also trying to find out how to use fragmented mp4s
