### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by yarzaryeni** [bentasker/HLS-Stream-Creator#27]
It would be great if the script can also resize the videos along with existing multiple bi-rate feature. Is there any plan to add resizing feature?

**Comment by bentasker** [comment]
You mean change the resolution?

That was added in [HLS-27](https://projects.bentasker.co.uk/jira_projects/browse/HLS-27.html). Details of how to use are in the [README](https://github.com/bentasker/HLS-Stream-Creator#multiple-resolutions)
